import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Menu,Search,Bell,ShoppingCart,Users,Tags,ClipboardList,DollarSign,Plus,Home as HomeIcon,Wallet,BarChart3,Settings,ChevronRight,X,Package,Receipt,Save,Calculator}from'lucide-react';import'./style.css';

const seed=[{id:1,name:'Origem Carmenere',category:'Casa Valduga',cost:49.54,price:64.90,promo:61.90,tags:['origem','casa valduga'],active:true},{id:2,name:'Origem Chardonnay',category:'Casa Valduga',cost:49.54,price:64.90,promo:61.90,tags:['casa valduga','chardonnay'],active:true}];
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function useStore(){const[p,setP]=useState(()=>JSON.parse(localStorage.getItem('videira-products')||'null')||seed);const[s,setS]=useState(()=>JSON.parse(localStorage.getItem('videira-settings')||'null')||{cardFee:4.2,packaging:1,fixed:0,targetMargin:25});useEffect(()=>localStorage.setItem('videira-products',JSON.stringify(p)),[p]);useEffect(()=>localStorage.setItem('videira-settings',JSON.stringify(s)),[s]);return{p,setP,s,setS}}
const nav=[['Home',HomeIcon],['Venda Rápida',ShoppingCart],['Clientes',Users],['Pedidos',ClipboardList],['Controle de Caixa',Wallet],['Produtos / Serviços',Tags],['Financeiro',DollarSign],['Estatísticas',BarChart3],['Configurações',Settings]];
function App(){const{p,setP,s,setS}=useStore();const[page,setPage]=useState('Home');const[drawer,setDrawer]=useState(false);const[selected,setSelected]=useState(null);const go=x=>{setPage(x);setDrawer(false);setSelected(null)};return <div className="app"><header><button onClick={()=>setDrawer(true)}><Menu/></button><div className="brand">Videira <b>Gestão</b></div><button><Bell/></button></header>
{drawer&&<><div className="shade" onClick={()=>setDrawer(false)}/><aside className="drawer"><div className="profile"><div className="avatar">VV</div><div><b>Videira Vinhoteca</b><small>Gestão empresarial</small></div><button onClick={()=>setDrawer(false)}><X/></button></div>{nav.map(([n,I])=><button className={page===n?'active':''} onClick={()=>go(n)} key={n}><I/>{n}<ChevronRight/></button>)}</aside></>}
<main>{selected?<ProductForm item={selected} products={p} setProducts={setP} settings={s} back={()=>setSelected(null)}/>:page==='Home'?<Dashboard products={p} go={go}/>:page==='Produtos / Serviços'?<Products products={p} edit={setSelected} add={()=>setSelected({id:Date.now(),name:'',category:'',cost:0,price:0,promo:0,tags:[],active:true,new:true})}/>:page==='Financeiro'?<Finance/>:page==='Pedidos'?<Empty title="Pedidos" text="Você não possui nenhum pedido nesse período." action="Cadastre um novo pedido"/>:page==='Configurações'?<Config s={s} setS={setS}/>:<Empty title={page} text="Módulo preparado para a próxima etapa." action="Em desenvolvimento"/>}</main>
<nav className="bottom">{[['Pedidos',ClipboardList],['Clientes',Users],['Produtos / Serviços',Tags],['Financeiro',DollarSign]].map(([n,I])=><button className={page===n?'on':''} onClick={()=>go(n)}><I/><span>{n==='Produtos / Serviços'?'Produtos':n}</span></button>)}<button className="fab" onClick={()=>setSelected({id:Date.now(),name:'',category:'',cost:0,price:0,promo:0,tags:[],active:true,new:true})}><Plus/></button></nav></div>}
function Dashboard({products,go}){return <><section className="hero"><h1>Olá, Videira</h1><p>Organize preços, custos e finanças em um só lugar.</p><div className="search"><Search/>Pesquise por ações...</div></section><div className="quick">{[['Venda Rápida',ShoppingCart],['Clientes',Users],['Produtos / Serviços',Tags],['Pedidos',ClipboardList],['Financeiro',DollarSign],['Configurações',Settings]].map(([n,I])=><button onClick={()=>go(n)}><I/><b>{n}</b></button>)}</div><section className="card summary"><h2>Resumo do negócio</h2><div><span>Produtos cadastrados<b>{products.length}</b></span><span>Produtos ativos<b>{products.filter(x=>x.active).length}</b></span></div></section></>}
function Products({products,edit,add}){const[q,setQ]=useState('');const list=products.filter(x=>x.name.toLowerCase().includes(q.toLowerCase()));return <><Title t="Produtos"/><div className="tabs"><b>Itens</b><span>Estoque</span><span>Categorias</span></div><div className="searchline"><Search/><input placeholder="Pesquisar em todos os itens" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="count">{list.length} produtos</div><div className="productlist">{list.map(x=><button className="product" onClick={()=>edit(x)}><div className="bottle">🍷</div><div><b>{x.name}</b><strong>{x.category}</strong><small>{x.tags.join(' · ')}</small></div><div className="prices"><del>{money(x.price)}</del><b>{money(x.promo||x.price)}</b></div></button>)}</div><button className="roundadd" onClick={add}><Plus/></button></>}
function ProductForm({item,products,setProducts,settings,back}){const[x,setX]=useState(item);const total=Number(x.cost||0)+Number(settings.packaging||0);const fee=Number(settings.cardFee||0)/100;const suggested=total/(1-Number(settings.targetMargin||0)/100-fee);const margin=x.price?((x.price-total)/x.price*100):0;const markup=x.cost?((x.price/x.cost-1)*100):0;const save=()=>{const y={...x,new:undefined};setProducts(v=>x.new?[...v,y]:v.map(a=>a.id===x.id?y:a));back()};return <><Title t={x.name||'Novo produto'} back={back}/><div className="form card"><div className="type"><b>Produto</b><span>Combo</span><span>Serviço</span></div><label>Nome<input value={x.name} onChange={e=>setX({...x,name:e.target.value})}/></label><label>Categoria<input value={x.category} onChange={e=>setX({...x,category:e.target.value})}/></label><div className="grid2"><label>Preço de custo<input type="number" step=".01" value={x.cost} onChange={e=>setX({...x,cost:e.target.value})}/></label><label>Preço de venda<input type="number" step=".01" value={x.price} onChange={e=>setX({...x,price:e.target.value})}/></label></div><label>Preço promocional / Pix<input type="number" step=".01" value={x.promo} onChange={e=>setX({...x,promo:e.target.value})}/></label><div className="calc"><Calculator/><div><b>Análise de preço</b><p>Custo + embalagem: {money(total)} · Markup: {markup.toFixed(1)}% · Margem bruta: {margin.toFixed(1)}%</p><p>Sugestão com margem-alvo + taxa: <strong>{money(suggested)}</strong></p></div></div><label className="switch">Disponível<input type="checkbox" checked={x.active} onChange={e=>setX({...x,active:e.target.checked})}/><i/></label></div><button className="save" onClick={save}><Save/>Salvar</button></>}
function Config({s,setS}){return <><Title t="Configurações"/><section className="card form"><h2>Precificação</h2><p className="muted">Valores usados automaticamente pela calculadora.</p><label>Taxa da maquininha — 1x (%)<input type="number" step=".01" value={s.cardFee} onChange={e=>setS({...s,cardFee:+e.target.value})}/></label><label>Embalagem por garrafa (R$)<input type="number" step=".01" value={s.packaging} onChange={e=>setS({...s,packaging:+e.target.value})}/></label><label>Margem-alvo (%)<input type="number" step=".1" value={s.targetMargin} onChange={e=>setS({...s,targetMargin:+e.target.value})}/></label><label>Gastos fixos mensais (R$)<input type="number" step=".01" value={s.fixed} onChange={e=>setS({...s,fixed:+e.target.value})}/></label></section><section className="card"><h2>Custos variáveis</h2><p className="muted">Na próxima etapa, cada insumo poderá ser cadastrado por unidade e vinculado aos produtos.</p></section></>}
function Finance(){return <><Title t="Financeiro"/><div className="tabs"><b>Transações</b><span>Categorias</span></div><Empty text="Você não possui nenhuma transação nesse período." action="Registre uma nova transação"/></>}
function Empty({title,text,action}){return <>{title&&<Title t={title}/>}<div className="empty"><Receipt/><p>{text}</p><b>{action}</b></div></>}
function Title({t,back}){return <div className="title">{back&&<button onClick={back}>←</button>}<h1>{t}</h1></div>}
createRoot(document.getElementById('root')).render(<App/>);